name: Tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        name: Set up Python
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        run: pip install poetry
      - name: Install repo
        run: poetry install --no-interaction --no-ansi
      - name: Run tests
        run: bash scripts/tests.sh
      - name: Upload coverage HTML
        if: ${{ matrix.python-version == '3.9' }}
        uses: actions/upload-artifact@v4
        with:
          name: htmlcov
          path: htmlcov
